name: Forum App 

on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: [self-hosted]
    steps:
    - name: Use Node js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        
    - name: Install pmnpm 
      uses: pnpm/action-setup@v4
      with:
        version: '9'

    - name: Install dependencies
      run: pnpm install

    - name: stop pm2 
      run: pnpm pm2 stop all

    - name: Copy .env file 
      run: |
        echo "${{secrets.ENV_FILE}}" .env

    - name: Buid nest js application 
      run: pnpm build

    - name: Start pm2
      run: pnpm pm2 start dist/main.js --name forum-app